### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by gabixdev** [KyokoBot/kyoko#24]
One of our goals is making Kyoko extendable by selfhosters, so the core API should be well documented to make developers life easier.

**Comment by chace86** [comment]
Can I take this one? I joined your Discord server and will ask questions there if needed.

**Comment by aredshaw** [comment]
Are you using REST APIs? If so, I might be able to help.
I would need to know the base path and endpoints.
Also, a list of possible methods and parameters.
And of course an API Key if one is required.

Have a good day,
Aaron

**Comment by gabixdev** [comment]
There's https://kyokobot.moe/api/ but it's not documented and there are only a few endpoints which are actually used (vote webhook and profile generator). Public release of the API is coming with the v3 rewrite (primarily image generation/stats endpoints).

**Comment by aredshaw** [comment]
The link you gave me returns a Page Not Found page.
This is what I need?
* The base path
* Endpoints
* All possible methods and parameters
* An API Key (If required)

Can you give me this? If so, I may be able to help with documentation.
Or are you connecting to the Discord server? In which case, you are using the Discord API docs.
