### ISSUE TITLE
Command frontend to customize prefixes.

### ISSUE THREAD

**Issue by gabixdev** [KyokoBot/Kyoko#39]

**Comment by chadramsey** [comment]
I'm interested in looking into this. Could you provide a little more detail into the issue?

**Comment by SamOphis** [comment]
custom prefixes are already internally supported by kyoko but there isn't any command "frontend" to customize that, meaning the only way prefixes can be changed is if you manually modify the database.

this issue basically wants you to create commands that administrators/server owners modify the prefix for their own guild. feel free to tag me or @gabixdev in kyoko's discord server if you need anymore detail on that, and good luck!
