### ISSUE TITLE
Improve queue system (save user who added the song, original link and more)

### ISSUE THREAD

**Issue by gabixdev** [KyokoBot/Kyoko#42]
- The queue should save info about user who queued the song.
- There should be a feature to remove duplicated songs from queue
- There should be a command to remove specified songs (via number) or all songs from specified user

**Comment by sidoknowia** [comment]
I would like to work on this issue

**Comment by gabixdev** [comment]
Just start working on it, if you have any questions join our Discord server, invite is in readme.

**Comment by gabixdev** [comment]
Fixed in #43
